const RAWG_API_BASE_URL = 'https://api.rawg.io/api'
const RAWG_DEFAULT_PAGE_SIZE = 24
const RAWG_DEFAULT_GENRE_PAGE_SIZE = 40
const RAWG_GAMES_ORDERING = '-rating'
const RAWG_GENRES_ORDERING = 'name'
const RAWG_API_KEY = import.meta.env.VITE_RAWG_API_KEY

export {
  RAWG_API_BASE_URL,
  RAWG_DEFAULT_PAGE_SIZE,
  RAWG_DEFAULT_GENRE_PAGE_SIZE,
  RAWG_GAMES_ORDERING,
  RAWG_GENRES_ORDERING,
  RAWG_API_KEY,
}
